# Generated by Django 5.1.6 on 2025-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceproposal',
            options={'verbose_name': 'service proposal', 'verbose_name_plural': 'Services Proposals'},
        ),
        migrations.AlterModelOptions(
            name='serviceproposalcategory',
            options={'verbose_name': 'service proposal category', 'verbose_name_plural': 'Services Proposals Categories'},
        ),
        migrations.AlterModelOptions(
            name='serviceproposalskill',
            options={'verbose_name': 'service proposal skill', 'verbose_name_plural': 'Services Proposals Skills'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'verbose_name': 'service request', 'verbose_name_plural': 'Services Requests'},
        ),
        migrations.AlterModelOptions(
            name='servicerequestsocials',
            options={'verbose_name': 'service request socials', 'verbose_name_plural': 'Services Requests Socials'},
        ),
        migrations.AlterModelOptions(
            name='usersocials',
            options={'verbose_name': 'user socials', 'verbose_name_plural': 'Users Socials'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
