# Generated by Django 5.1.6 on 2025-04-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0004_alter_servicerequestsocials_service_request_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProposalCategory',
            new_name='ServiceCategory',
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'service category', 'verbose_name_plural': 'Services Categories'},
        ),
    ]
