# Generated by Django 5.1.6 on 2025-04-14 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0005_rename_serviceproposalcategory_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(default='Autre | Other', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requests', to='app_models.servicecategory'),
        ),
    ]
