# Generated by Django 5.1.6 on 2025-04-14 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0006_servicerequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproposal',
            name='category',
            field=models.ForeignKey(default='Autre | Other', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='proposals', to='app_models.servicecategory'),
        ),
    ]
