# Generated by Django 5.1.6 on 2025-04-14 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0007_alter_serviceproposal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproposal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='app_models.servicecategory'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app_models.servicecategory'),
        ),
    ]
